### ISSUE TITLE
How did u manage to do this?

### ISSUE THREAD

**Issue by veso266** [Yanndroid/Samsung-My-Files-Root-Extension#1]
Hello there, was wondering, how did you manage to figure how how to make an extension for Samsung MyFiles

Did the sorce code for MyFiles ever leak?

Was always wondering how samsung makes app plugins for their apps (MyFiles and Notes (the addon that converts old Notes into the newer format)

**Comment by Yanndroid** [comment]
I reverse engineered / decompiled the apk and then it's just a matter of finding what makes it work. I did this for a couple of [other things](https://oneuiproject.github.io/hidden-api/) too.

**Comment by veso266** [comment]
Oh, you did that

After looking at the apk for networkstorage, it seams you were lucky and the apk is not obfuscacated

I wanted to reverse engeneer FMRadio once (com.sec.android.app.fm): https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/

But the thing was obfuscacated

I even looked for the source code in samsung open source
https://opensource.samsung.com/uploadList?menuItem=mobile

Hoping I would find it there (since the app has some opensource disclaimer), but sadly it wasnt there eather

Its interesting that some apps are obfuscacated while other are not, its like that they eather forgot to turn ProGuard on or just didnt care

Regarding your network storage root exstension, its great, I only wish there would be a swich so I could eather use it or real network storage

Not sure if extensions can have their own ui to add a simple swich that would (if on) eather pass calls to real network storage or provide its own root storage if swich is off

**Comment by Yanndroid** [comment]
Yeah, Samsung apps are pretty random regarding obfuscation, and unfortunately most of their new apps have it. It's also a huge problem for the [libraries](https://github.com/OneUIProject) I'm maintaining, since we're relying on new apps without obfuscation and minify.

I think it would still have been possible if the Network Storage Manager was obfuscated, since it's not too complex and things like AndroidManifest can't be obfuscated.
And no, the extension for MyFiles can't have it's own UI. The way I implemented all of this is super hacky, I mean just take a look at the menu for adding storage locations :sweat_smile: .
A possibility to merge both functionalities though would be to add back all the server stuff and then just a one "server" which points to the root directory instead. But at this point you might as well just make an app that host a local smb server for the root directory.

The open source disclaimer is only for open source libraries they use, not for their apps. I also tried to find something on their websites, github, etc. But not even the huge data leak form a while back had something interesting for us.

What is it that you want to get from FMRadio? If it's a core functionality, maybe take a look at older versions which aren't obfuscated.
